title: "Dave's Dev Blog"
description: ""
author: "David Hibbitts"
email: ""
markdown: kramdown
remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
include:
  - _headers
  - _redirects
  - .htpasswd
  - assets
show_downloads: false
future: true

# URL Configuration
baseurl: ""  # the subpath of your site, e.g. /blog
url: ""      # the base hostname & protocol
permalink: /posts/:title/
