markdown: kramdown
remote_theme: pages-themes/slate@v0.2.0
include: [_headers]
title: "Dave's Dev Blog"kdown: kramdown
remote_theme: pages-themes/slate@v0.2.0
title: "Dave’s Dev Blog"
description: ""
author: "David Hibbitts"
email: "REMOVED_EMAIL"
show_downloads: false
# Optional links in the footer
footer-links:
  email: REMOVED_EMAIL
  linkedin: davehibbitts
  github: digitaldave0
