title: "Just a random place to post :)"
description: "A blog about AI, DevOps, programming, and more"
author: "David Hibbitts"
email: ""
markdown: kramdown
theme: jekyll-theme-chirpy
plugins:
  - jekyll-paginate
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache
include:
  - _headers
  - _redirects
  - .htpasswd
  - assets
show_downloads: false
future: true

# URL Configuration
baseurl: "/dev-blog"  # the subpath of your site, e.g. /blog
url: "https://digitaldave0.github.io"      # the base hostname & protocol
permalink: /posts/:title/

# Chirpy specific settings
avatar: /assets/img/blog_image.png  # Your blog avatar image
timezone: Europe/London  # Adjust to your timezone
lang: en

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive
    tag: archive
  permalinks:
    category: "/categories/:name/"
    tag: "/tags/:name/"

# Social links (configured in _data/contact.yml)
# contact:
#   - type: github
#     icon: "fab fa-github"
#     url: "https://github.com/username"

# Comments (optional)
# comments:
#   active: disqus
#   disqus:
#     shortname: your-disqus-shortname

# Analytics (optional)
# analytics:
#   google:
#     id: "your-google-analytics-id"
